//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePad {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The USB Client EDP module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientEDP usbClientEDP;
        
        /// <summary>The Display TE35 module using sockets 15, 16, 17 and 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayTE35 displayTE35;
        
        /// <summary>The Serial Camera L1 module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SerialCameraL1 serialCameraL1;
        
        /// <summary>The SD Card module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>The Tunes module using socket 18 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Tunes tunes;
        
        /// <summary>The WiFi RS21 module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.WiFiRS21 wifiRS21;
        
        /// <summary>The TempHumid SI70 module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.TempHumidSI70 tempHumidSI70;
        
        /// <summary>The LightSense module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LightSense lightSense;
        
        /// <summary>The BreadBoard X1 module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.BreadBoardX1 breadBoardX1;
        
        /// <summary>The CellularRadio module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.CellularRadio cellularRadio;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZRaptor Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZRaptor)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZRaptor();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientEDP = new GTM.GHIElectronics.USBClientEDP(8);
            this.displayTE35 = new GTM.GHIElectronics.DisplayTE35(15, 16, 17, 14);
            this.serialCameraL1 = new GTM.GHIElectronics.SerialCameraL1(12);
            this.sdCard = new GTM.GHIElectronics.SDCard(9);
            this.tunes = new GTM.GHIElectronics.Tunes(18);
            this.wifiRS21 = new GTM.GHIElectronics.WiFiRS21(3);
            this.tempHumidSI70 = new GTM.GHIElectronics.TempHumidSI70(1);
            this.lightSense = new GTM.GHIElectronics.LightSense(2);
            this.breadBoardX1 = new GTM.GHIElectronics.BreadBoardX1(6);
            this.cellularRadio = new GTM.GHIElectronics.CellularRadio(4);
        }
    }
}
